services:
  - type: web
    name: launchstatellc-backend
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
